---

db_host: postgis
redis_cache: redis

services:
  - name: postgis
    templates: ../k8s/database/
    pvc_name: db
    sub_path: database
    databases:
      - zrc
      - drc
      - ztc
      - brc
      - nrc
      - ac
      - token-issuer
      - vrl
      - deploy

  - name: redis
    templates: ../k8s/cache/

  - name: ac
    templates: ../k8s/ac/
    image_tag: '1.0.0'

  - name: brc
    templates: ../k8s/brc/
    image_tag: '1.0.1.post0'

  - name: drc
    templates: ../k8s/drc/
    image_tag: '1.0.1.post0'
    min_upload_size: 4294967296  # 4GB

  - name: nrc
    templates: ../k8s/nrc/
    image_tag: '1.0.0.post1'

  - name: zrc
    templates: ../k8s/zrc/
    image_tag: '1.0.1.post0'

  - name: ztc
    templates: ../k8s/ztc/
    image_tag: '1.0.0.post4'

  - name: docs
    templates: ../k8s/docs

  - name: token-issuer
    templates: ../k8s/tokens
    image_tag: '0.6.2'
    redis_host: redis-test
    redis_db: 7
    host: zaken-auth.vng.cloud

  - name: vrl
    templates: ../k8s/vrl/
    image_tag: '0.5.6'

  - name: demo
    templates: ../k8s/demo/

  - name: deploy
    templates: ../k8s/deploy/

ingress:
  name: ref-implementatie
  instance: zgw-stable
  services:
    # Primary APIs
    - host: zaken-api.vng.cloud
      name: zrc
    - host: documenten-api.vng.cloud
      name: drc
    - host: catalogi-api.vng.cloud
      name: ztc
    - host: autorisaties-api.vng.cloud
      name: ac
    - host: besluiten-api.vng.cloud
      name: brc
    - host: notificaties-api.vng.cloud
      name: nrc
    # Documentation
    - host: zaakgerichtwerken.vng.cloud
      name: docs
      port: 80
    # Supporting services
    - host: referentielijsten-api.vng.cloud
      name: vrl
    - host: zaken-auth.vng.cloud
      name: token-issuer
    - host: zgw-demo.vng.cloud
      name: demo
    - host: deploy-bot-zgw.vng.cloud
      name: deploy
