openapi: '3.0.0'
info:
  title: Generieke componenten voor de Zaakgericht-werken API's
  version: '1.0'

components:
  responses:
    '400':
      description: Bad request
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van
            een specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ValidatieFout'
    '401':
      description: Unauthorized
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van
            een specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '403':
      description: Forbidden
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van
            een specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '406':
      description: Not acceptable
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van
            een specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '409':
      description: Conflict
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van
            een specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '410':
      description: Gone
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van
            een specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '412':
      description: Precondition failed
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van
            een specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '415':
      description: Unsupported media type
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van
            een specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '429':
      description: Too many requests
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van
            een specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'
    '500':
      description: Internal server error
      headers:
        API-version:
          schema:
            type: string
          description: 'Geeft een specifieke API-versie aan in de context van
            een specifieke aanroep. Voorbeeld: 1.2.1.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Fout'

  schemas:
    Fout:
      required:
      - code
      - title
      - status
      - detail
      - instance
      type: object
      properties:
        type:
          title: Type
          description: URI referentie naar het type fout, bedoeld voor developers
          type: string
        code:
          title: Code
          description: Systeemcode die het type fout aangeeft
          type: string
          minLength: 1
        title:
          title: Title
          description: Generieke titel voor het type fout
          type: string
          minLength: 1
        status:
          title: Status
          description: De HTTP status code
          type: integer
        detail:
          title: Detail
          description: Extra informatie bij de fout, indien beschikbaar
          type: string
          minLength: 1
        instance:
          title: Instance
          description: URI met referentie naar dit specifiek voorkomen van de fout.
            Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld.
          type: string
          minLength: 1
    FieldValidationError:
      required:
      - name
      - code
      - reason
      type: object
      properties:
        name:
          title: Name
          description: Naam van het veld met ongeldige gegevens
          type: string
          minLength: 1
        code:
          title: Code
          description: Systeemcode die het type fout aangeeft
          type: string
          minLength: 1
        reason:
          title: Reason
          description: Uitleg wat er precies fout is met de gegevens
          type: string
          minLength: 1
    ValidatieFout:
      required:
      - code
      - title
      - status
      - detail
      - instance
      - invalidParams
      type: object
      properties:
        type:
          title: Type
          description: URI referentie naar het type fout, bedoeld voor developers
          type: string
        code:
          title: Code
          description: Systeemcode die het type fout aangeeft
          type: string
          minLength: 1
        title:
          title: Title
          description: Generieke titel voor het type fout
          type: string
          minLength: 1
        status:
          title: Status
          description: De HTTP status code
          type: integer
        detail:
          title: Detail
          description: Extra informatie bij de fout, indien beschikbaar
          type: string
          minLength: 1
        instance:
          title: Instance
          description: URI met referentie naar dit specifiek voorkomen van de fout.
            Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld.
          type: string
          minLength: 1
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/FieldValidationError'
    AuditTrail:
      required:
      - bron
      - actie
      - resultaat
      - hoofdObject
      - resource
      - resourceUrl
      - resourceWeergave
      - wijzigingen
      type: object
      properties:
        uuid:
          title: Uuid
          description: Unieke identificatie van de audit regel.
          type: string
          format: uuid
        bron:
          title: Bron
          description: 'De naam van het component waar de wijziging in is gedaan.


            Uitleg bij mogelijke waarden:


            * `ac` - Autorisatiecomponent

            * `nrc` - Notificatierouteringcomponent

            * `zrc` - Zaakregistratiecomponent

            * `ztc` - Zaaktypecatalogus

            * `drc` - Documentregistratiecomponent

            * `brc` - Besluitregistratiecomponent

            * `kic` - Klantinteractiescomponent'
          type: string
          enum:
          - ac
          - nrc
          - zrc
          - ztc
          - drc
          - brc
          - kic
        requestId:
          title: Request id
          description: Een globaal "request" ID om een verzoek door het netwerk heen
            te traceren.
          type: string
          maxLength: 255
        applicatieId:
          title: Applicatie id
          description: Unieke identificatie van de applicatie, binnen de organisatie.
          type: string
          maxLength: 100
        applicatieWeergave:
          title: Applicatie weergave
          description: Vriendelijke naam van de applicatie.
          type: string
          maxLength: 200
        gebruikersId:
          title: Gebruikers id
          description: Unieke identificatie van de gebruiker die binnen de organisatie
            herleid kan worden naar een persoon.
          type: string
          maxLength: 255
        gebruikersWeergave:
          title: Gebruikers weergave
          description: Vriendelijke naam van de gebruiker.
          type: string
          maxLength: 255
        actie:
          title: Actie
          description: 'De uitgevoerde handeling.


            De bekende waardes voor dit veld zijn hieronder aangegeven,                         maar
            andere waardes zijn ook toegestaan


            Uitleg bij mogelijke waarden:


            * `create` - Object aangemaakt

            * `list` - Lijst van objecten opgehaald

            * `retrieve` - Object opgehaald

            * `destroy` - Object verwijderd

            * `update` - Object bijgewerkt

            * `partial_update` - Object deels bijgewerkt'
          type: string
          maxLength: 50
          minLength: 1
        actieWeergave:
          title: Actie weergave
          description: Vriendelijke naam van de actie.
          type: string
          maxLength: 200
        resultaat:
          title: Resultaat
          description: HTTP status code van de API response van de uitgevoerde handeling.
          type: integer
          maximum: 599
          minimum: 100
        hoofdObject:
          title: Hoofd object
          description: De URL naar het hoofdobject van een component.
          type: string
          format: uri
          maxLength: 1000
          minLength: 1
        resource:
          title: Resource
          description: Het type resource waarop de actie gebeurde.
          type: string
          maxLength: 50
          minLength: 1
        resourceUrl:
          title: Resource url
          description: De URL naar het object.
          type: string
          format: uri
          maxLength: 1000
          minLength: 1
        toelichting:
          title: Toelichting
          description: Toelichting waarom de handeling is uitgevoerd.
          type: string
        resourceWeergave:
          title: Resource weergave
          description: Vriendelijke identificatie van het object.
          type: string
          maxLength: 200
          minLength: 1
        aanmaakdatum:
          title: Aanmaakdatum
          description: De datum waarop de handeling is gedaan.
          type: string
          format: date-time
          readOnly: true
        wijzigingen:
          $ref: '#/components/schemas/Wijzigingen'
    Wijzigingen:
      title: Wijzigingen
      type: object
      properties:
        oud:
          title: Oud
          description: Volledige JSON body van het object zoals dat bestond voordat
            de actie heeft plaatsgevonden.
          type: object
        nieuw:
          title: Nieuw
          description: Volledige JSON body van het object na de actie.
          type: object
